language: ruby
dist: trusty
sudo: false
before_install:
  - gem update bundler
before_script:
  - bundle update
cache: bundler
rvm:
  - 1.8.7-head
  - 1.9.2-p330
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.7.0
  - ruby-head
  - jruby-18mode
  - jruby-1.7.27
  - jruby-9.1.17.0
  - jruby-9.2.0.0
  - jruby-head
  - rbx-2.71828182
  - rbx-3.107
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.71828182
